name: finews_module
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  intl: ^0.17.0
  json_annotation: ^4.5.0
  math_expressions: ^2.3.0
  auto_size_text: ^3.0.0 
  get_storage: ^2.0.3
  pin_code_fields: ^7.3.0
  pdfx: ^2.0.1+2
  share: ^2.0.4
  
  package_info: ^2.0.2
  connectivity: ^3.0.6
  device_info_plus: ^3.2.1
  flutter_sticky_header: ^0.6.1
  crypto: ^3.0.1
  cupertino_icons: ^1.0.2
  internet_file: ^1.0.0+2
  smooth_page_indicator: ^1.0.0+2
  pull_to_refresh: ^2.0.0
  shimmer: ^2.0.0
  simple_tooltip: ^1.0.0
  flutter_custom_tabs: ^1.0.4
  universal_html: ^2.0.8
  animated_flip_counter: ^0.2.4
  sticky_headers: ^0.2.0
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  rxdart: ^0.27.4
  loading_animation_widget: ^1.2.0
  pinput: ^2.2.7
  url_launcher: ^6.1.0
  flutter_html: ^3.0.0-alpha.5
  html: ^0.15.0
  path_provider: ^2.0.11
  flutter_svg: ^1.0.3
  webview_flutter: 3.0.4

#  flutter_inappwebview: ^5.4.3+7
  flutter_inappwebview:
    git: https://github.com/CodeEagle/flutter_inappwebview
  #  flutter_spinkit: ^4.1.2+1
  #  loading: ^1.0.2

  #  candlesticks: ^2.1.0
  http: ^0.13.4
  #  candlesticks:
  #    git:
  #      url: https://github.com/zstart6490/candlesticks2
  #      ref: develop
  firebase_core: ^1.22.0
  firebase_analytics: ^9.3.4
  timeago: ^3.3.0
  flutter_html_all: ^3.0.0-alpha.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.10
  json_serializable: ^6.1.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
   assets:
     - assets/images/
     - assets/images/FiNews.png
     - assets/images/icon_stock.png
     - assets/images/ic_send_dis.png
     - assets/images/ic_reply.png
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
